### ISSUE TITLE
Pulsator offset during Rotations

### ISSUE THREAD

**Issue by winkelsdorf** [shu223/Pulsator#1]
Hi,

I changed the layout constraint of the y-Axis in your demo:
<img width="1103" alt="screenshot 2016-04-19 14 15 07" src="https://cloud.githubusercontent.com/assets/1413291/14638770/3ce081e4-0639-11e6-88b1-1f1a98ab91ba.png">

Any easy way to fix the position of the Pulsator?
<img width="362" alt="screenshot 2016-04-19 14 15 21" src="https://cloud.githubusercontent.com/assets/1413291/14638784/4dacc1fe-0639-11e6-943d-245c08a13fe3.png">

Cheers,
Frederik

**Comment by shu223** [comment]
I fixed the example. Now the position of `pulsator` layer will follow the position of `sourceView` layer.

**Comment by winkelsdorf** [comment]
Thank you! That works 👍 

The only glitch I see is during rotation. The layer is updated asynchronously from the ```sourceView```. I tried experimenting with the ```transitionContext``` but was unable to find a quick solution.

I tried fixing it with this in the ViewController:
```swift
    override func viewWillTransitionToSize(size: CGSize, withTransitionCoordinator coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransitionToSize(size, withTransitionCoordinator: coordinator)

        coordinator.animateAlongsideTransition({ context in
                // during transition
                sourceView.layoutIfNeeded()
                self.pulsator.position = sourceView.center
            }, completion: { context in
                // after transition
        })
    }
```

Unfortunately without success.

Here's a video, just change the demo to allow all device orientations and toggle slow animations before rotating the simulator (happens on device too):

![pulsator rotation glitch](https://cloud.githubusercontent.com/assets/1413291/14674520/b9328082-0704-11e6-89a8-0c8beeebbf26.gif)

Thank you for your help!

**Comment by shu223** [comment]
Thanks, I don't care for rotation for now, so if you can fix & send a pull request, it's so helpful.

**Comment by winkelsdorf** [comment]
Sure, I'll have a look into this and report back! Can take some time, as I likely start to integrate GPS functionality (where it's used) in summer.

Should I leave this open as reminder?

**Comment by shu223** [comment]
Much appreciated! Please close this issue, and then send me a pull request or open a new issue when you have something new.

**Comment by winkelsdorf** [comment]
Ok, that's what we'll do :) 

And thank you very much for your work with this great component!
