### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by eoboite** [shu223/Pulsator#13]
Hey thank you for this great library. I'm having issues implementing pulsator into my swift 2,3 project. I'm using cocoapods and set the version to 0.1.1 but it throws an error saying it can not find QuartzCore.

How do I implement it into my project for swift 2.3?

**Comment by asif-lango** [comment]
I am facing the same issue. Will you please fix this issue for swift 2.3?

**Comment by eoboite** [comment]
I used the objective-c version instead. It's compatible with swift.
