### ISSUE TITLE
Not working on Swift 2.3

### ISSUE THREAD

**Issue by timlin19880207** [shu223/Pulsator#14]
I ran the pod install, however I couldn't create the Pulsator instance. It seems like the library was not properly load from pod.

**Comment by timlin19880207** [comment]
After change Podfile to version 0.1.1, it does work. But somehow I had to clean the DerivedData, clean the project and rebuild. Otherwise, it should no such module when I import "Pulsator"

**Comment by davij** [comment]
not working on xcode 7.3.1 here's the podlock file:
![podlock](https://cloud.githubusercontent.com/assets/7143635/18885952/d5e82e9a-84bb-11e6-8290-e45fa7edc5ff.png)
