### ISSUE TITLE
how to center pulse behind image

### ISSUE THREAD

**Issue by pprevalon** [shu223/Pulsator#17]
the pulse is on the top left of the image i can add it to the center of the image.
thank you in advance
![screen shot 2017-01-13 at 4 46 33 am](https://cloud.githubusercontent.com/assets/19171619/21925393/4e8c683c-d94b-11e6-817d-884ad0e51e2b.png)

**Comment by marciliojrs** [comment]
```
override func viewDidLoad() {
    ...
    imageView.layer.superlayer?.insertSublayer(pulsator, below: imageView.layer)
    ...
}

override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()

    pulsator.position = imageView.layer.position
}
```

**Comment by shu223** [comment]
I hope this was resolved. Thanks @marciliojrs for your support!

**Comment by SirWellington** [comment]
I believe this should be centered by default as well, or at the very least customizable by the API.

**Comment by dmwesterhoff** [comment]
I added this line and it set the position correctly:

```swift
pulsator.position = sourceView.layer.position
`
That way I didn't need to override that method out just to correct the position, not sure if there is ramifications to this method for other use cases but it worked as well in my case and isolated my code to a single method.

**Comment by LoopingLouieX** [comment]
I've added the following code and that worked for me:
`pulsator.position = CGPoint(x: yourView.bounds.width / 2, y: yourView.bounds.height / 2)`
