### ISSUE TITLE
Animation disappear when switching app from background to foreground

### ISSUE THREAD

**Issue by vincent-peng** [shu223/Pulsator#2]
Hi,
First thank you for the great work on this nice component.
I have noticed when switching from background to foreground, the pulse animation disappear.
This is reproducible in the example app too.

![may-03-2016 10-00-32](https://cloud.githubusercontent.com/assets/9654118/14971482/25e392b4-1116-11e6-9c55-331c8df1e89b.gif)

**Comment by damirstuhec** [comment]
Same here.

**Comment by shu223** [comment]
I'm sorry, I'll fix soon.
