### ISSUE TITLE
Cocoapods version update.

### ISSUE THREAD

**Issue by KimDarren** [shu223/Pulsator#24]
There is a lot of difference between `0.3.0` tag and `master` branch.
Would you publish the newest source code to CocoaPods?

**Comment by shu223** [comment]
@KimDarren  Thanks, but I don't think it's "a lot". The differences are being fixed a typo (for an internal function) and being fixed a storyboard file in a demo project...That's why I didn't release it. Nothing would be changed for the library user app, I think.

**Comment by KimDarren** [comment]
@shu223 Thanks for your answer. It was my misunderstanding 😢 sorry.
