### ISSUE TITLE
Use of unresolved identifier 'Pulsator'

### ISSUE THREAD

**Issue by TheMasquerader** [shu223/Pulsator#28]
Hey guys,

I've been trying for two days to get Pulsator to work, but no matter what I do, I keep getting the `Use of unresolved identifier 'Pulsator'` error.
I have a simple Podfile:
```
platform :ios, '10.0'
use_frameworks!

target 'JumpingJacksAlarm' do
    pod 'Pulsator', '~> 0.3.0'
end
```
and `pod install` reports success. I also tried `pod update`, project clean, restarts, reinstalls, and pretty much any suggestions I was able to find.

I would really appreciate it if you could help me figure out what's going on. Please let me know if there's any additional info I can provide.

Thank you in advance!

**Comment by designfrontier** [comment]
Adding `import Pulsator` in the file worked for me
