### ISSUE TITLE
Can't get the pulse positioned behind a button...

### ISSUE THREAD

**Issue by designfrontier** [shu223/Pulsator#36]
Also setting `pulsator.position` makes it disappear completely?

```
       pulsator.position = self.view.center
        pulsator.numPulse = 5
        pulsator.radius = 70
        pulsator.repeatCount = .greatestFiniteMagnitude
        pulsator.animationDuration = 3
        pulsator.backgroundColor = UIColor(red: 0, green: 0.755, blue: 0.756, alpha: 1).cgColor
        button.layer.insertSublayer(pulsator, below: button.layer)
        pulsator.start()
```

**Comment by designfrontier** [comment]
with the position line commented out it appears slightly above and to the right of the button

**Comment by abhishekb21** [comment]
Facing similar issue

**Comment by SweetSuri** [comment]
Hi, try changing  this line: button.layer.insertSublayer(pulsator, below: button.layer)
with: "buttons PARENT VIEW".layer.insertSublayer(pulsator, below: button.layer)
This works for me hope it helps :).

**Comment by vishnu-cz** [comment]
@designfrontier Hey this must be happening because you are setting it before subview layout properly. You need to paste this code in viewDidLayoutSubviews function , it should work fine

**Comment by rami965** [comment]
Try putting it in `viewDidAppear` 
```swift
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    guard addVoiceNoteButton.layer.sublayers?.contains(pulsator) != true else { return }
    button.layer.insertSublayer(pulsator, at: .zero)
}
```
