### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by tmarkovski** [shu223/Pulsator#42]
Carthage fails for some reason with the following error:

`*** Building scheme "Pulsator" in Pulsator.xcodeproj
Failed to write to /Users/geddoff/Git/tmarkovski/indyapp/Carthage/Build/Mac/Pulsator.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “Pulsator.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/geddoff/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/Pulsator/0.5.1/Build/Intermediates.noindex/ArchiveIntermediates/Pulsator/BuildProductsPath/Release-iphoneos/Pulsator.framework, NSFilePath=/Users/geddoff/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/Pulsator/0.5.1/Build/Intermediates.noindex/ArchiveIntermediates/Pulsator/BuildProductsPath/Release-iphoneos/Pulsator.framework, NSUnderlyingError=0x7fd8bec97b50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

I simply added the entry to the Cartfile. Any ideas?

**Comment by J8Fish** [comment]
I have the same issue.

**Comment by shu223** [comment]
@J8Fish Thank you for trying. I've added a release tag. Could you try it again?

**Comment by J8Fish** [comment]
It works! Thank you so much.
