### ISSUE TITLE
Won't compile on Swift 4.2

### ISSUE THREAD

**Issue by 15458434** [shu223/Pulsator#44]
I'm getting compile issues when trying to compile this on Swift 4.2. I have a fix ready, but can't create a branch on the repo. Can you fix that?

**Comment by Ashotych** [comment]
Same issue..

**Comment by sean-howard** [comment]
Just opened https://github.com/shu223/Pulsator/pull/45 for this.

**Comment by 15458434** [comment]
Too bad...  I've already created my own version of CAReplicatorLayer that does exactly this. I'll post the source code later on.

**Comment by shu223** [comment]
I can't push the new podspec for now with a validation error for [this problem](https://github.com/CocoaPods/CocoaPods/issues/7708). Seems to need to wait for a new version of CocoaPods. I'm sorry for the inconvenience.

**Comment by tapannathvani** [comment]
I am facing the same issue.. Can i know when you are going to update the pod ?

**Comment by alexpersian** [comment]
To get around this issue for the time being you can use this in your podfile instead.

`pod 'Pulsator', :git => 'https://github.com/shu223/Pulsator.git', :tag => '0.5.3'`

**Comment by talezion** [comment]
@shu223 Any plans for releasing Swift 4.2? As a tag will not work, as I am using it as a dependency in my podspec. 0.5.3 is not recognised.

**Comment by shu223** [comment]
I've just published the podspec for 0.5.3 on CocoaPods! I'm sorry for this late release.
