### ISSUE TITLE
Pulsator animaton does not appear

### ISSUE THREAD

**Issue by minaMagedNaeem** [shu223/Pulsator#47]
my code:
`
let pulsator = Pulsator()
override func viewDidLoad() {
        super.viewDidLoad()
        shoppieImage.layer.superlayer!.insertSublayer(pulsator, below: shoppieImage.layer)
        pulsator.numPulse = 1
        pulsator.animationDuration = 1
        pulsator.repeatCount = 0
        pulsator.pulseInterval = 0.25
        pulsator.backgroundColor = ShopXStyle.yellowColor.cgColor
        pulsator.radius = 200
        pulsator.name = "pulsator"
        pulsator.start()
}

override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        view.layer.layoutIfNeeded()
        pulsator.position = shoppieImage.center
    }`

**Comment by minaMagedNaeem** [comment]
I fixed it, it just needed some alteration in pulsator's properties.

**Comment by ZkHaider** [comment]
What were the alterations?

**Comment by minaMagedNaeem** [comment]
pulsator.radius = view.bound.height / 2 + 20

**Comment by fukemy** [comment]
still not appear for me
