### ISSUE TITLE
Pulsator in Custom Map Annotation

### ISSUE THREAD

**Issue by mrsnax** [shu223/Pulsator#5]
Hi,

I was to trying add Pulsator into my project, but the annotation cant play pulse, what I'm doing wrong? My code below is : 

```
#annotationView = MKAnnotationView(annotation: annotation, reuseIdentifier: "pin")
annotationView!.canShowCallout = true
annotationView!.image = UIImage(named: "cars2x")
            
annotationView!.layer.superlayer?.insertSublayer(pulsator, below: annotationView!.layer)
pulsator.numPulse = 3
pulsator.radius = 240.0
pulsator.start()
```

The code is ok, no found errors, but pulse can't show up :/

**Comment by shu223** [comment]
Hi,
I added an example & a playground which indicate how to use it for map annotations. I hope those will be helpful.

**Comment by kidsid-Ixigo** [comment]
@shu223 you haven't explained how to show it behind of annotation image?

**Comment by fukemy** [comment]
pulsator not show when add to imageview, can someone help?
