### ISSUE TITLE
Adding via SPM does not work in Xcode 11.3.1

### ISSUE THREAD

**Issue by igorkulman** [shu223/Pulsator#58]
Any reason the `Package.swift` starts with `// swift-tools-version:5.2`? 

Because of this the package cannot be added via Xcode 11.3.1. I think there is nothing Swift 5.2. specific in the source code.

**Comment by shu223** [comment]
@igorkulman  Oh, I just didn't know. I just fixed it with `// swift-tools-version:5.0`!

**Comment by igorkulman** [comment]
Thanks
