### ISSUE TITLE
Drop support for iOS 8

### ISSUE THREAD

**Issue by natalia-osa** [shu223/Pulsator#59]
When installing your library Xcode 12 informs about a warning:

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

The warning is for Pulsator library. I'm installing it via SPM, so no possibility to change it on the fly. With cocoapods people can add post-install script.

Can you bump the minimal target? iOS 8 is a very old system, a tiny percentage, probably not more than 0.5, is still using it.

**Comment by shu223** [comment]
@natalia-osa  Thank you for letting me know that! I've pushed a commit to update the target version.
